### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by danni551** [Inori/GPCS4#141]
I get an error when i try to build it
>In file included from arch\x86\x86_helpers.cpp:18:
1>In file included from arch\x86/x86_helpers.h:21:
1>C:\Users\danie\Downloads\GPCS4-0.2.2\3rdParty\xbyak\xbyak.h(16,6): error : invalid token at start of a preprocessor expression
1>Die Erstellung des Projekts "TinyDBR.vcxproj" ist abgeschlossen -- ERROR

**Comment by Inori** [comment]
I remember this is a [known issue](https://github.com/Inori/GPCS4/blob/master/3rdParty/xbyak/xbyak.h#L13)
What's the version of clang are you using?

**Comment by Brutal-sam** [comment]
yupp same error here too and it was on 13.0.0 and 14.0.4, also tried an old 9.0.0

**Comment by Brutal-sam** [comment]
@Inori you talked about running demos, can you name some compatible supported demos? I think you talking about ps4 pkgs right?

**Comment by Inori** [comment]
I remember the problem solved when I updated my clang version (not 100% sure though).
How do you change your clang version?
I used this [config file](https://github.com/Inori/GPCS4/blob/master/Misc/Directory.build.props).

**Comment by Brutal-sam** [comment]
tried using the config file to change to different versions of clang but the same issue remains, maybe it's not a clang version issue.
we know it's not meant for the end user yet but reporting those issues can be helpful to you as a dev

**Comment by Inori** [comment]
It seems it's because clang doesn't recognize `not` token, but I don't know why I can compile on all of my machines.
You can try to comment out those 3 lines, it should be safe.

**Comment by Brutal-sam** [comment]
commenting out the 3 lines just created more errors, like memory_order_relaxed is not defined, and function call not allowed.
but it's all good now I sent this to my dev friend and he built it for me so I have it running samples now, hope you fix the support for We Are Doomed or something else. 
![1](https://user-images.githubusercontent.com/94696121/175796674-4cd05ad8-81e7-47f3-9687-481d75a6443e.JPG)
![Capture](https://user-images.githubusercontent.com/94696121/175796675-858f84ab-72e2-4381-8390-efe50eda1217.JPG)

**Comment by Inori** [comment]
@Brutal-sam 
`memory_order_relaxed` issue should have been fixed in more recent code base.
I haven't met `function call not allowed` issue myself, seems for some reason you are not using correct compiler.
What did your friend say about the compiling errors?

**Comment by Brutal-sam** [comment]
@Inori he didn't say anything about errors but said this: "just left the default compiler of the project, maybe some missing installation here made the compiler be changed automatically", if it's okay can you share screenshots of how to change the compiler to the right one?

**Comment by gandalfthewhite19890404** [comment]
> `memory_order_relaxed` issue should have been fixed in more recent code base.

No, it still exist even in dev branch.
IDK how you're building your project, instead of arguing just setup CI for project,  all users's compiling tries will stop.

**Comment by gandalfthewhite19890404** [comment]
Also in your sources these files are missing
#include <boost/predef/version_number.h>
#include <boost/predef/hardware/simd/arm/versions.h>

**Comment by xgrommx** [comment]
> Also in your sources these files are missing #include <boost/predef/version_number.h> #include <boost/predef/hardware/simd/arm/versions.h>

https://levelup.gitconnected.com/the-definite-guide-on-compiling-and-linking-boost-c-libraries-for-visual-studio-projects-c79464d7282d

**Comment by Inori** [comment]
Using VS2022 and LLVM 16.0.6, should be all fixed.
